### ISSUE TITLE
ERROR: Service 'mfe' failed to build : Build failed

### ISSUE THREAD

**Issue by agusmakmun** [overhangio/tutor-mfe#55]
I'm getting this error when plugin of `mfe` is enabled, but when I disabled it working fine.

```
 > [account-dev 3/5] RUN npm clean-install --no-audit --no-fund --registry=https://registry.npmjs.org/   && rm -rf ~/.npm:
#15 20.23 npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
#15 20.24 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#15 23.96 npm WARN deprecated superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
#15 25.25 npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
#15 25.48 npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
#15 27.88 npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
#15 29.33 npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
#15 29.35 npm WARN deprecated resolve-url-loader@5.0.0-beta.1: version 5 is now released
#15 31.92 npm WARN deprecated redux-devtools-extension@2.13.9: Package moved to @redux-devtools/extension.
#15 36.40 npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
#15 37.65 npm notice
#15 37.65 npm notice New minor version of npm available! 8.5.0 -> 8.12.1
#15 37.65 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.12.1>
#15 37.65 npm notice Run `npm install -g npm@8.12.1` to update!
#15 37.65 npm notice
#15 37.65 npm ERR! code ERR_SOCKET_TIMEOUT
#15 37.65 npm ERR! network Socket timeout
#15 37.65 npm ERR! network This is a problem related to network connectivity.
#15 37.65 npm ERR! network In most cases you are behind a proxy or have bad network settings.
#15 37.65 npm ERR! network
#15 37.65 npm ERR! network If you are behind a proxy, please make sure that the
#15 37.65 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
#15 37.68
#15 37.68 npm ERR! A complete log of this run can be found in:
#15 37.68 npm ERR!     /root/.npm/_logs/2022-06-14T08_21_07_298Z-debug-0.log
------
executor failed running [/bin/sh -c npm clean-install --no-audit --no-fund --registry=$NPM_REGISTRY   && rm -rf ~/.npm]: exit code: 1
ERROR: Service 'mfe' failed to build : Build failed
Error: Command failed with status 1: docker-compose -f /Users/agus/Library/Application Support/tutor/env/local/docker-compose.yml -f /Users/agus/Library/Application Support/tutor/env/local/docker-compose.prod.yml -f /Users/agus/Library/Application Support/tutor/env/local/docker-compose.tmp.yml --project-name tutor_local up --remove-orphans --build -d
```

```bash
(env-open-edx) ➜  openedx-tutor git:(feat/initial) ✗ tutor plugins disable mfe
Disabling plugin mfe...
    env - removing folder: /Users/agus/Library/Application Support/tutor/env/plugins/mfe/build
    env - removing folder: /Users/agus/Library/Application Support/tutor/env/plugins/mfe/apps
Plugin mfe disabled
Configuration saved to /Users/agus/Library/Application Support/tutor/config.yml
You should now re-generate your environment with `tutor config save`.
(env-open-edx) ➜  openedx-tutor git:(feat/initial) ✗ tutor config save
Configuration saved to /Users/agus/Library/Application Support/tutor/config.yml
Environment generated in /Users/agus/Library/Application Support/tutor/env
(env-open-edx) ➜  openedx-tutor git:(feat/initial) ✗ tutor plugins list
android    	(disabled)	14.0.0
discovery  	(disabled)	14.0.0
ecommerce  	(disabled)	14.0.0
forum      	(disabled)	14.0.0
license    	(disabled)	14.0.0
mfe        	(disabled)	14.0.0
minio      	(disabled)	14.0.0
notes      	(disabled)	14.0.0
pdso       	          	0.0.1
richie     	(disabled)	14.0.0
webui      	(disabled)	14.0.0
xqueue     	(disabled)	14.0.0
(env-open-edx) ➜  openedx-tutor git:(feat/initial) ✗
```

**Comment by agusmakmun** [comment]
The same issue where someone faced: https://askubuntu.com/q/1407927/713890

**Comment by regisb** [comment]
(I'm closing this on behalf of @arbrandes, he plugin maintainer).

Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing

**Comment by agusmakmun** [comment]
Moved here: https://discuss.openedx.org/t/error-service-mfe-failed-to-build-build-failed/7568
but still didn't get any reply.

**Comment by SeifHafri** [comment]
I am facing the same issue, has anyone figured it out ? I am running ubuntu 20.04 and this is my npm config : 
`; "user" config from /home/seif/.npmrc

fetch-retry-maxtimeout = 120000 
fetch-retry-mintimeout = 20000 
registry = "http://registry.npmjs.org/" 

; node bin location = /home/seif/.nvm/versions/node/v16.19.1/bin/node
; node version = v16.19.1
; npm local prefix = /home/seif
; npm version = 8.19.3
; cwd = /home/seif
; HOME = /home/seif
; Run `npm config ls -l` to show all defaults.`

**Comment by SeifHafri** [comment]
facing the same issue and cannot seem to figure it out

**Comment by warpet** [comment]
I respond here because the thread on openedx.org is closed and no replies are allowed anymore. It took me a while to figure out a solution, so maybe other people which have the same issue have a simple solution.

This happens because the npm registry allows only a number of TCP connections from the same IP address.
The Dockerfile generated by [plugin.py](https://github.com/overhangio/tutor-mfe/blob/master/tutormfe/plugin.py) of tutormfe is really huge and contains quite a lot of npm calls (some for every app), which all run in parallel and each of them installs a whole tree of packages, which of course open a lot of connections to the npm registry per each parallel build instance.

So, due to the docker layer built in parallel, they create so many concurrent HTTP connections to the npm registry, that they will be refused after a certain number of connections and the build fails. Mostly on the same position in code.

I resolved this by setting max-parallelism to 1, by doing the following:

`
$ cat >/etc/buildkitd.toml  <<EOF
[worker.oci]
  max-parallelism=1
EOF
$ docker buildx create --use --bootstrap --name tutorbuilder --driver docker-container --config /etc/buildkitd.toml
$ tutor images build mfe --docker-arg --builder=tutorbuilder
`

This then takes a long, long time to build, but it goes through.
In order to shorten build-time, build it in parallel before, let it fail and then rebuild with max-parallelism=1, so many layers are cached and are not rebuilt anymore when it runs serialized.

**Comment by regisb** [comment]
> This happens because the npm registry allows only a number of TCP connections from the same IP address.

Oh wow, I had no idea. This is the first I hear about this limitation. Is it due to the [maxsockets](https://docs.npmjs.com/cli/v10/using-npm/config#maxsockets) config parameter? Could we resolve the issue by reducing this parameter instead of reducing paralellism? By default, this value is 15. Should we attempt to reduce it to, say, 5?

**Comment by warpet** [comment]
I was not able to build also with max-parallelism=2, but only with serialized, so max-parallelism=1
But it helps definitively building before parallelized, so that layers are cached and then continue serialized after failure.
Maybe tcp connection limiting could help, but that seems not to be implemented so well yet.

**Comment by regisb** [comment]
> This happens because the npm registry allows only a number of TCP connections from the same IP address.

Do you have further evidence that the ERR_SOCKET_TIMEOUT or ECONNRESET errors are caused by too many TCP connections from the same IP? I could not find information about this online.

**Comment by warpet** [comment]
Unfortunately nothing except the same error message on the ticket posted by the OP.
Also because it is encapsulated inside the container, so even the error log is not accessible anymore after failure the container is gone.
I think about maybe count the concurrent connections to the repo on the perimeter firewall. But even that does not give proof.
