### ISSUE TITLE
Customizing MFEs documentation still refer to Tutor plugin v0 API?

### ISSUE THREAD

**Issue by sambapete** [overhangio/tutor-mfe#81]
Instructions on the README page on how to customize MFEs still refer to Tutor plugin v0 API
https://github.com/overhangio/tutor-mfe/#customising-mfes

It would need to be updated to Tutor plugin v1 API in the future.

**Comment by arbrandes** [comment]
@sambapete, do you refer to dynamic configuration (done via the database)?  If so, yes, the README will have to be updated as part of https://github.com/overhangio/tutor-mfe/pull/69.  We're still not sure if the current static configuration will actually be removed in Olive, or if it will continue to work alongside dynamic config.

**Comment by sambapete** [comment]
@arbrandes In this case, I was testing the courseware.microfrontend_course_exit_page waffle flag in our Nutmeg instance. 

The pages that are displayed afterwards make reference to the SEARCH_CATALOG_URL that isn't currently set in the tutor-MFE environment in Nutmeg. I noticed it because the link to "search in the catalogue" went nowhere. Therefore, I had to create my own tutor plugin under tutor-plugins in order to patch it so that SEARCH_CATALOG_URL was defined. 

Since @regisb changed the API from v0 to v1 for tutor-plugins, I was surprised to see a reference to the old v0 API in the README.

Obviously, I would prefer to use the dynamic config, but I believe it is not yet available in Nutmeg.

**Comment by arbrandes** [comment]
> I was surprised to see a reference to the old v0 API in the README.

Just for the record, it looks like v0/yaml-based plugins are still going to be supported, going forward.  Regis' recent post:

"I have no issue whatsoever with YAML-formatted plugins. I think it’s perfectly fine to distribute your plugin in the form of a YAML file. Still, I think that the v1 API is better, more capable, and thus I would encourage you to take the time to migrate your plugins." (https://discuss.openedx.org/t/whats-the-deal-with-tpa-hinted-links-in-nutmeg-olive/8436/25?u=arbrandes)

But yes, since updating to v1 is recommended, I agree it would make sense to port the README as an example.  Let's leave this issue open.  Thanks!

**Comment by arbrandes** [comment]
Fixed by https://github.com/overhangio/tutor-mfe/pull/100
